title: Jacob Holt
logo: /assets/img/headshot.jpg
description: I am a PhD candidate at Dartmouth College in the [Nadell Lab](https://nadell-lab.org/).
show_downloads: false
theme: jekyll-theme-minimal
