title: Jacob Holt
#logo: /assets/img/headshot_circl.png
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JakeH15"
